sudo: required
dist: trusty

language: node_js

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- nvm install 6.1.0
- npm install
- npm prune

script:
- npm run dist
