sudo: required
dist: trusty

language: node_js

addons:
  apt:
    packages:
      - icnsutils

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
- "npm set config optional true"

install:
- nvm install 6.1.0
- npm install

script:
- npm run dist
