platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

test_script:
  - npm run test

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6.1.0 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run dist-win
